### PR TITLE
fix: bump kubernetes- and openshift-client to 7.0.0 (#247)

### LINKED ISSUE #247: bump kubernetes-client to 7.0.0
related to https://github.com/redhat-developer/intellij-openshift-connector/issues/921, https://github.com/redhat-developer/intellij-knative/issues/257

Support for multiple kubernetes config files will be available in kubernetes-client 7.0 (see https://github.com/fabric8io/kubernetes-client/issues/6240, https://github.com/redhat-developer/intellij-kubernetes/issues/779). We'll have to bump the kubernetes-client 7.0 in intellij-kubernetes, intellij-openshift-connector and intellij-tekton.

### PR DESCRIPTION
**Pull request by adietish**
fixes #247

### CODE REVIEW

**Comment by adietish** [comment]
kubernetes-client 7.0 was released: https://repo1.maven.org/maven2/io/fabric8/kubernetes-client/7.0.0/

**Comment by adietish** [comment]
weird enough tests only fail when run on IC-2024.2...

File: src/main/java/com/redhat/devtools/intellij/common/utils/ConfigWatcher.java [hunk 1]
```diff
@@ -38,30 +38,22 @@ public class ConfigWatcher implements Runnable {
...
 
     public interface Listener {
-        void onUpdate(ConfigWatcher source, Config config);
+        void onUpdate(Config updatedConfig);
     }
 
-    public ConfigWatcher(String config, Listener listener) {
-        this(Paths.get(config), listener);
+    public ConfigWatcher(Listener listener) {
+        this(Config.getKubeconfigFilenames().stream().map(Paths::get).toList(), listener, new HighSensitivityRegistrar());
```
Comment (adietish) [inline src/main/java/com/redhat/devtools/intellij/common/utils/ConfigWatcher.java:45]: `ConfigWatcher` does not need to get the path to the config file. It is using the Client config which merged all the config files that were merged when it (auto-) configured

File: src/main/java/com/redhat/devtools/intellij/common/utils/ConfigWatcher.java [hunk 2]
```diff
@@ -38,30 +38,22 @@ public class ConfigWatcher implements Runnable {
...
+    protected ConfigWatcher(List<Path> configs, Listener listener, HighSensitivityRegistrar registrar) {
         this.configs = configs;
         this.listener = listener;
         this.registrar = registrar;
     }
 
     @Override
     public void run() {
-        watch((Config config) -> listener.onUpdate(this, config));
+        watch(listener::onUpdate);
```
Comment (adietish) [inline src/main/java/com/redhat/devtools/intellij/common/utils/ConfigWatcher.java:56]: notify listeners of a change in the client config (not individual kubeconf files)

File: src/main/java/com/redhat/devtools/intellij/common/utils/ConfigWatcher.java [hunk 3]
```diff
@@ -70,11 +62,11 @@ public void close() throws IOException {
         }
     }
 
-    private void watch(Consumer<Config> consumer) {
+    private void watch(Consumer<Config> listener) {
```
Comment (adietish) [inline src/main/java/com/redhat/devtools/intellij/common/utils/ConfigWatcher.java:65]: simple rename, "listener" is more precise.

File: src/main/java/com/redhat/devtools/intellij/common/utils/ConfigWatcher.java [hunk 4]
```diff
@@ -136,12 +128,13 @@ private void register(Path path, WatchService service, HighSensitivityRegistrar
...
         }
 
-        private void watch(Consumer<Config> consumer, WatchService service) throws InterruptedException {
+        private void watch(Consumer<io.fabric8.kubernetes.client.Config> listener, WatchService service) throws InterruptedException {
             for (WatchKey key = service.take(); key != null; key = service.take()) {
                 key.pollEvents().forEach((event) -> {
                     Path changed = getAbsolutePath(directory, (Path) event.context());
                     if (isConfigPath(changed)) {
-                        consumer.accept(loadConfig(changed));
+                        Config config = new ConfigBuilder().build();
```
Comment (adietish) [inline src/main/java/com/redhat/devtools/intellij/common/utils/ConfigWatcher.java:136]: dont load a particular kubeconf. Have the kubernetes-client load and merge all the files that are configured.

File: src/main/java/com/redhat/devtools/intellij/common/utils/ToolsConfigHelper.java [hunk 5]
```diff
@@ -0,0 +1,33 @@
...
+ * Copyright (c) 2024 Red Hat, Inc.
+ * Distributed under license by Red Hat, Inc. All rights reserved.
+ * This program is made available under the terms of the
+ * Eclipse Public License v2.0 which accompanies this distribution,
+ * and is available at http://www.eclipse.org/legal/epl-v20.html
+ *
+ * Contributors:
+ * Red Hat, Inc. - initial API and implementation
+ ******************************************************************************/
+package com.redhat.devtools.intellij.common.utils;
```
Comment (adietish) [inline src/main/java/com/redhat/devtools/intellij/common/utils/ToolsConfigHelper.java:11]: separated methods that deal with the tools config from the methods that deal with the kubernernetes-client config. -> created a new class `ToolsConfigHelper`

**Comment by adietish** [comment]
> weird enough tests only fail when run on IC-2024.2...

Bumping mockito to 5.x fixes the issue 

Didnt find out why `IC-2024.2` (and only this version, not latter 24.3) is running tests using `jdk21` even though the build specifies `jdk17`.
The issue is that byte buddy within mockito 4.x wont support classes that are compiled with `jdk21`.
```java
                Caused by:
                java.lang.IllegalArgumentException: Java 21 (65) is not supported by the current version of Byte Buddy which officially supports Java 19 (63) - update Byte Buddy or set net.bytebuddy.experimental as a VM property
                    at net.bytebuddy.utility.OpenedClassReader.of(OpenedClassReader.java:96)
```
Mockito 5.x includes a version of the byte buddy that supports `jdk21`.

**Comment by adietish** [comment]
@sbouchet: This PR for intellij-common is ready. Please review.

File: gradle.properties [hunk 6]
```diff
@@ -3,7 +3,7 @@ nexusUser=invalid
 nexusPassword=invalid
 
 # IntelliJ Platform Properties -> https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html#configuration-intellij-extension
-ideaVersion=2024.2
+ideaVersion=2024.3
```
Comment (sbouchet) [inline gradle.properties:6]: please also update the ci to validate against this version ( i know it's this one used in OS-matrix build, but this will provide us verifier reports )

**Review by sbouchet — APPROVED** [review]
beside ci workflow update that can be done in anoher PR, LGTM.
