### PR TITLE
fix: corrected javadoc warnings (#53)

### LINKED ISSUE #53: fix: correct javadoc warnings
```
> Task :javadoc
/Users/andredietisheim/Documents/jboss-workspaces/intellij-common/src/main/java/com/redhat/devtools/intellij/common/utils/ConfigHelper.java:126: warning: no description for @param
     * @param thisContext
       ^
/Users/andredietisheim/Documents/jboss-workspaces/intellij-common/src/main/java/com/redhat/devtools/intellij/common/utils/ConfigHelper.java:127: warning: no description for @param
     * @param thatContext
       ^
/Users/andredietisheim/Documents/jboss-workspaces/intellij-common/src/main/java/com/redhat/devtools/intellij/common/utils/DownloadHelper.java:119: warning: no description for @throws
         * @throws IOException
           ^
/Users/andredietisheim/Documents/jboss-workspaces/intellij-common/src/main/java/com/redhat/devtools/intellij/common/utils/HighSensitivityRegistrar.java:43: warning: no @return
        protected boolean isMac() {
                          ^
/Users/andredietisheim/Documents/jboss-workspaces/intellij-common/src/main/java/com/redhat/devtools/intellij/common/utils/HighSensitivityRegistrar.java:55: warning: no description for @return
         * @return
           ^
/Users/andredietisheim/Documents/jboss-workspaces/intellij-common/src/main/java/com/redhat/devtools/intellij/common/utils/HighSensitivityRegistrar.java:79: warning: no @return
        protected Class<Modifier> getSensitivityWatchEventModifierClass() throws ClassNotFoundException {
                                  ^
/Users/andredietisheim/Documents/jboss-workspaces/intellij-common/src/main/java/com/redhat/devtools/intellij/common/utils/HighSensitivityRegistrar.java:79: warning: no @throws for java.lang.ClassNotFoundException
        protected Class<Modifier> getSensitivityWatchEventModifierClass() throws ClassNotFoundException {
                                  ^
/Users/andredietisheim/Documents/jboss-workspaces/intellij-common/src/main/java/com/redhat/devtools/intellij/common/tree/StructureTreeModelFactory.java:28: warning: no description for @throws
         * @throws IllegalAccessException
           ^
/Users/andredietisheim/Documents/jboss-workspaces/intellij-common/src/main/java/com/redhat/devtools/intellij/common/tree/StructureTreeModelFactory.java:29: warning: no description for @throws
         * @throws InvocationTargetException
           ^
/Users/andredietisheim/Documents/jboss-workspaces/intellij-common/src/main/java/com/redhat/devtools/intellij/common/tree/StructureTreeModelFactory.java:30: warning: no description for @throws
         * @throws InstantiationException
           ^
/Users/andredietisheim/Documents/jboss-workspaces/intellij-common/src/main/java/com/redhat/devtools/intellij/common/tree/StructureTreeModelFactory.java:31: warning: no description for @throws
         * @throws NoSuchMethodException
           ^
11 warnings
```

### PR DESCRIPTION
**Pull request by adietish**
fixes #53

### CODE REVIEW

File: src/main/java/com/redhat/devtools/intellij/common/utils/ConfigHelper.java [hunk 1]
```diff
@@ -123,8 +123,8 @@ public static boolean areEqual(Config kubeConfig, io.fabric8.kubernetes.client.C
      *     <li>extensions</li>
      * </ul>
      *
-     * @param thisContext
-     * @param thatContext
+     * @param thisContext the fist context to compare
```
Comment (jeffmaury) [inline src/main/java/com/redhat/devtools/intellij/common/utils/ConfigHelper.java:126]: typo

**Review by jeffmaury — CHANGES_REQUESTED** [review]

**Review by jeffmaury — APPROVED** [review]
LGTM
