### PR TITLE
fix: correct incompatibilities to IC-2024.1 (#207)

### LINKED ISSUE #207: fix IC-2024.1 compatibility issues
dependency to https://github.com/redhat-developer/intellij-kubernetes/issues/719

See https://plugins.jetbrains.com/plugin/15921-kubernetes-by-red-hat/edit/versions/stable/463954
image

### PR DESCRIPTION
**Pull request by adietish**
fixes #207

### CODE REVIEW

File: src/main/java/com/redhat/devtools/intellij/common/utils/UIHelper.java [hunk 1]
```diff
@@ -14,10 +14,18 @@
 import com.intellij.ide.ui.laf.darcula.DarculaLaf;
 import com.intellij.openapi.application.ApplicationManager;
 
-import javax.swing.UIManager;
+import javax.swing.*;
```
Comment (sbouchet) [inline src/main/java/com/redhat/devtools/intellij/common/utils/UIHelper.java:17]: please avoid starts import :)
